/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/newenv/Barrel cactus.glb -o app/components/env/BarrelCactus.tsx --types --transform --keepnames --precision 2 
Files: public/models/newenv/Barrel cactus.glb [3.67MB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Barrel cactus-transformed.glb [95.6KB] (97%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    BarrelCactus_mesh: THREE.Mesh;
  };
  materials: {
    BarrelCactus_mat: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/newenv/Barrel cactus-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="BarrelCactus_mesh"
        geometry={nodes.BarrelCactus_mesh.geometry}
        material={materials.BarrelCactus_mat}
      />
    </group>
  );
}

useGLTF.preload("/models/newenv/Barrel cactus-transformed.glb");
