/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Bridge.glb -o app/components/env/Bridge.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Bridge.glb [26.21KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Bridge-transformed.glb [2.78KB] (89%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Bridge1: THREE.Mesh;
  };
  materials: {
    WoodBridge1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Bridge-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Bridge1"
        geometry={nodes.Bridge1.geometry}
        material={materials.WoodBridge1}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Bridge-transformed.glb");
