/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Campfire.glb -o app/components/env/Campfire.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Campfire.glb [48.57KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Campfire-transformed.glb [5KB] (90%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Campfire_Cylinder009-Mesh"]: THREE.Mesh;
    ["Campfire_Cylinder009-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    Stone: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Campfire-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Campfire_Cylinder009-Mesh"
        geometry={nodes["Campfire_Cylinder009-Mesh"].geometry}
        material={materials.Stone}
      />
      <mesh
        name="Campfire_Cylinder009-Mesh_1"
        geometry={nodes["Campfire_Cylinder009-Mesh_1"].geometry}
        material={materials.Wood}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Campfire-transformed.glb");
