/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/newenv/Desert.glb -o app/components/env/Desert.tsx --types --transform --keepnames --precision 2 
Files: public/models/newenv/Desert.glb [1.82MB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Desert-transformed.glb [157.76KB] (91%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Node: THREE.Mesh;
  };
  materials: {
    Plane: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/newenv/Desert-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Node"
        geometry={nodes.Node.geometry}
        material={materials.Plane}
      />
    </group>
  );
}

useGLTF.preload("/models/newenv/Desert-transformed.glb");
