/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Flower Bed.glb -o app/components/env/FlowerBed.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Flower Bed.glb [5.01KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Flower Bed-transformed.glb [2.32KB] (54%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    FlowerBed2_1: THREE.Mesh;
    FlowerBed2_2: THREE.Mesh;
  };
  materials: {
    ConcreteFlowerBed2: THREE.MeshStandardMaterial;
    GroundFlowerBed5: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Flower Bed-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="FlowerBed2_1"
        geometry={nodes.FlowerBed2_1.geometry}
        material={materials.ConcreteFlowerBed2}
      />
      <mesh
        name="FlowerBed2_2"
        geometry={nodes.FlowerBed2_2.geometry}
        material={materials.GroundFlowerBed5}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Flower Bed-transformed.glb");
