/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Grass B.glb -o app/components/env/GrassB.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Grass B.glb [28.76KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Grass B-transformed.glb [10.4KB] (64%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    grass_B: THREE.Mesh;
  };
  materials: {
    tiny_treats_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Grass B-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="grass_B"
        geometry={nodes.grass_B.geometry}
        material={materials.tiny_treats_1}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Grass B-transformed.glb");
