/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Hedge Corner.glb -o app/components/env/HedgeCorner.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Hedge Corner.glb [33KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Hedge Corner-transformed.glb [11.42KB] (65%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    hedge_corner: THREE.Mesh;
  };
  materials: {
    tiny_treats_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Hedge Corner-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="hedge_corner"
        geometry={nodes.hedge_corner.geometry}
        material={materials.tiny_treats_1}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Hedge Corner-transformed.glb");
