/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/newenv/Humvee.glb -o app/components/env/Humvee.tsx --types --transform --keepnames --precision 2 
Files: public/models/newenv/Humvee.glb [556.94KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Humvee-transformed.glb [47.98KB] (91%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    humvee001: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/newenv/Humvee-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="humvee001"
        geometry={nodes.humvee001.geometry}
        material={materials.Material}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/newenv/Humvee-transformed.glb");
