/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/newenv/Prickly pear cactus.glb -o app/components/env/PricklyPearCactus.tsx --types --transform --keepnames --precision 2 
Files: public/models/newenv/Prickly pear cactus.glb [307.92KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Prickly pear cactus-transformed.glb [39.38KB] (87%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    prickly_pear_cactus: THREE.Mesh;
  };
  materials: {
    None: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/newenv/Prickly pear cactus-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="prickly_pear_cactus"
        geometry={nodes.prickly_pear_cactus.geometry}
        material={materials.None}
      />
    </group>
  );
}

useGLTF.preload("/models/newenv/Prickly pear cactus-transformed.glb");
