/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/newenv/Rainbow With Clouds.glb -o app/components/env/RainbowWithClouds.tsx --types --transform --keepnames --precision 2 
Files: public/models/newenv/Rainbow With Clouds.glb [204.85KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Rainbow With Clouds-transformed.glb [23.75KB] (88%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    pDisc4_1: THREE.Mesh;
    pDisc4_2: THREE.Mesh;
  };
  materials: {
    rainbow: THREE.MeshStandardMaterial;
    clouds: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/newenv/Rainbow With Clouds-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="pDisc4_1"
        geometry={nodes.pDisc4_1.geometry}
        material={materials.rainbow}
      />
      <mesh
        name="pDisc4_2"
        geometry={nodes.pDisc4_2.geometry}
        material={materials.clouds}
      />
    </group>
  );
}

useGLTF.preload("/models/newenv/Rainbow With Clouds-transformed.glb");
