/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Road.glb -o app/components/env/Road.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Road.glb [12.37KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Road-transformed.glb [3.15KB] (75%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Road: THREE.Mesh;
  };
  materials: {
    Mat: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Road-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Road"
        geometry={nodes.Road.geometry}
        material={materials.Mat}
      />
    </group>
  );
}

useGLTF.preload("/Road-transformed.glb");
