/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Rock.glb -o app/components/env/Rock.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Rock.glb [5.17KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Rock-transformed.glb [1.52KB] (71%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Rock5: THREE.Mesh;
  };
  materials: {
    Rock5: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Rock-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Rock5"
        geometry={nodes.Rock5.geometry}
        material={materials.Rock5}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Rock-transformed.glb");
