/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Street Lantern.glb -o app/components/env/StreetLantern.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Street Lantern.glb [37.34KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Street Lantern-transformed.glb [11.54KB] (69%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    street_lantern: THREE.Mesh;
  };
  materials: {
    tiny_treats_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Street Lantern-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="street_lantern"
        geometry={nodes.street_lantern.geometry}
        material={materials.tiny_treats_1}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Street Lantern-transformed.glb");
