/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Table.glb -o app/components/env/Table.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Table.glb [18.51KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Table-transformed.glb [1.99KB] (89%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Table1: THREE.Mesh;
  };
  materials: {
    Table1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Table-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Table1"
        geometry={nodes.Table1.geometry}
        material={materials.Table1}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Table-transformed.glb");
