/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Tent.glb -o app/components/env/Tent.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Tent.glb [16.26KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Tent-transformed.glb [3.06KB] (81%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Tent_Cube001-Mesh"]: THREE.Mesh;
    ["Tent_Cube001-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    Tent_M: THREE.MeshStandardMaterial;
    Tent_S: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Tent-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Tent_Cube001-Mesh"
        geometry={nodes["Tent_Cube001-Mesh"].geometry}
        material={materials.Tent_M}
      />
      <mesh
        name="Tent_Cube001-Mesh_1"
        geometry={nodes["Tent_Cube001-Mesh_1"].geometry}
        material={materials.Tent_S}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Tent-transformed.glb");
