/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Tree from the savanna.glb -o app/components/env/TreeSavanna.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Tree from the savanna.glb [65.36KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Tree from the savanna-transformed.glb [7.8KB] (88%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Tree2_1: THREE.Mesh;
    Tree2_2: THREE.Mesh;
  };
  materials: {
    Leaves: THREE.MeshStandardMaterial;
    Tree: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Tree from the savanna-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="Tree2"
        position={[-0.01, 2.7, -0.43]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      >
        <mesh
          name="Tree2_1"
          geometry={nodes.Tree2_1.geometry}
          material={materials.Leaves}
        />
        <mesh
          name="Tree2_2"
          geometry={nodes.Tree2_2.geometry}
          material={materials.Tree}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/enviroment/Tree from the savanna-transformed.glb");
