/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/enviroment/Tree Large.glb -o app/components/env/TreeLarge.tsx --types --transform --keepnames --precision 2 
Files: public/models/enviroment/Tree Large.glb [35.67KB] > /Users/mendsalbert/Documents/safariVerse/app/components/env/Tree Large-transformed.glb [11.81KB] (67%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    tree_large: THREE.Mesh;
  };
  materials: {
    tiny_treats_1: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/enviroment/Tree Large-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="tree_large"
        geometry={nodes.tree_large.geometry}
        material={materials.tiny_treats_1}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/enviroment/Tree Large-transformed.glb");
