/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Bear.glb -o app/components/models/animals/Bear.tsx 
Files: public/models/animals/Bear.glb [120.96KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Bear-transformed.glb [19.83KB] (84%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["08bearFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.123"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Bear-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="08bearFinal"
        geometry={nodes["08bearFinal"].geometry}
        material={materials["Material.123"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Bear-transformed.glb");
