/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Bird-h5IzAUdltz.glb -o app/components/models/animals/Bird-h5IzAUdltz.tsx 
Files: public/models/animals/Bird-h5IzAUdltz.glb [193.76KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Bird-h5IzAUdltz-transformed.glb [36.68KB] (81%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["24birdFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.091"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Bird-h5IzAUdltz-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="24birdFinal"
        geometry={nodes["24birdFinal"].geometry}
        material={materials["Material.091"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Bird-h5IzAUdltz-transformed.glb");
