/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Bird.glb -o app/components/models/animals/Bird.tsx 
Files: public/models/animals/Bird.glb [97.65KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Bird-transformed.glb [20KB] (80%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["23smolbirdFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.124"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Bird-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="23smolbirdFinal"
        geometry={nodes["23smolbirdFinal"].geometry}
        material={materials["Material.124"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Bird-transformed.glb");
