/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Bizon.glb -o app/components/models/animals/Bizon.tsx 
Files: public/models/animals/Bizon.glb [152.29KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Bizon-transformed.glb [25.83KB] (83%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["04bizonFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.119"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Bizon-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="04bizonFinal"
        geometry={nodes["04bizonFinal"].geometry}
        material={materials["Material.119"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Bizon-transformed.glb");
