/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Cat.glb -o app/components/models/animals/Cat.tsx 
Files: public/models/animals/Cat.glb [119.91KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Cat-transformed.glb [20.29KB] (83%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["02catFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.093"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Cat-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="02catFinal"
        geometry={nodes["02catFinal"].geometry}
        material={materials["Material.093"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Cat-transformed.glb");
