/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Chick.glb -o app/components/models/animals/Chick.tsx 
Files: public/models/animals/Chick.glb [97.85KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Chick-transformed.glb [18.55KB] (81%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["22smolchikenFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.126"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Chick-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="22smolchikenFinal"
        geometry={nodes["22smolchikenFinal"].geometry}
        material={materials["Material.126"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Chick-transformed.glb");
