/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Chicken.glb -o app/components/models/animals/Chicken.tsx 
Files: public/models/animals/Chicken.glb [120.95KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Chicken-transformed.glb [21.13KB] (83%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["21chikenFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.128"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Chicken-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="21chikenFinal"
        geometry={nodes["21chikenFinal"].geometry}
        material={materials["Material.128"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Chicken-transformed.glb");
