/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Corgi.glb -o app/components/models/animals/Corgi.tsx 
Files: public/models/animals/Corgi.glb [148.26KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Corgi-transformed.glb [25.27KB] (83%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["14dogFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.131"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Corgi-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="14dogFinal"
        geometry={nodes["14dogFinal"].geometry}
        material={materials["Material.131"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Corgi-transformed.glb");
