/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Cow.glb -o app/components/models/animals/Cow.tsx 
Files: public/models/animals/Cow.glb [197.2KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Cow-transformed.glb [35.18KB] (82%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["13cowFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.130"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Cow-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="13cowFinal"
        geometry={nodes["13cowFinal"].geometry}
        material={materials["Material.130"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Cow-transformed.glb");
