/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Deer-bLT2gJHPPt.glb -o app/components/models/animals/Deer-bLT2gJHPPt.tsx 
Files: public/models/animals/Deer-bLT2gJHPPt.glb [210.44KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Deer-bLT2gJHPPt-transformed.glb [36.37KB] (83%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["09deerFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.138"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Deer-bLT2gJHPPt-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="09deerFinal"
        geometry={nodes["09deerFinal"].geometry}
        material={materials["Material.138"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Deer-bLT2gJHPPt-transformed.glb");
