/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Dog-9bqPCxOyrk.glb -o app/components/models/animals/Dog-9bqPCxOyrk.tsx 
Files: public/models/animals/Dog-9bqPCxOyrk.glb [155.78KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Dog-9bqPCxOyrk-transformed.glb [24.02KB] (85%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["12dogFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.129"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Dog-9bqPCxOyrk-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="12dogFinal"
        geometry={nodes["12dogFinal"].geometry}
        material={materials["Material.129"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Dog-9bqPCxOyrk-transformed.glb");
