/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Duck.glb -o app/components/models/animals/Duck.tsx 
Files: public/models/animals/Duck.glb [113.01KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Duck-transformed.glb [17.74KB] (84%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["03duckFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.118"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Duck-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="03duckFinal"
        geometry={nodes["03duckFinal"].geometry}
        material={materials["Material.118"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Duck-transformed.glb");
