/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Fox.glb -o app/components/models/animals/Fox.tsx 
Files: public/models/animals/Fox.glb [207.93KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Fox-transformed.glb [36.78KB] (82%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["01foxFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.092"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Fox-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="01foxFinal"
        geometry={nodes["01foxFinal"].geometry}
        material={materials["Material.092"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Fox-transformed.glb");
