/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Frog.glb -o app/components/models/animals/Frog.tsx 
Files: public/models/animals/Frog.glb [155.98KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Frog-transformed.glb [25.64KB] (84%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["11frogFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.127"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Frog-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="11frogFinal"
        geometry={nodes["11frogFinal"].geometry}
        material={materials["Material.127"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Frog-transformed.glb");
