/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Giraffe.glb -o app/components/models/animals/Giraffe.tsx 
Files: public/models/animals/Giraffe.glb [113.68KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Giraffe-transformed.glb [16.65KB] (85%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["18girafFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.136"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Giraffe-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="18girafFinal"
        geometry={nodes["18girafFinal"].geometry}
        material={materials["Material.136"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Giraffe-transformed.glb");
