/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Horse.glb -o app/components/models/animals/Horse.tsx 
Files: public/models/animals/Horse.glb [142.01KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Horse-transformed.glb [22.3KB] (84%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["17horseFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.089"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Horse-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="17horseFinal"
        geometry={nodes["17horseFinal"].geometry}
        material={materials["Material.089"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Horse-transformed.glb");
