/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Lizard.glb -o app/components/models/animals/Lizard.tsx 
Files: public/models/animals/Lizard.glb [134.51KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Lizard-transformed.glb [26.79KB] (80%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["15lizardFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.132"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Lizard-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="15lizardFinal"
        geometry={nodes["15lizardFinal"].geometry}
        material={materials["Material.132"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Lizard-transformed.glb");
