/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Penguin.glb -o app/components/models/animals/Penguin.tsx 
Files: public/models/animals/Penguin.glb [103.18KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Penguin-transformed.glb [21.2KB] (79%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["06penguinFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.121"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Penguin-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="06penguinFinal"
        geometry={nodes["06penguinFinal"].geometry}
        material={materials["Material.121"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Penguin-transformed.glb");
