/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Shark.glb -o app/components/models/animals/Shark.tsx 
Files: public/models/animals/Shark.glb [169.32KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Shark-transformed.glb [29.57KB] (83%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["07sharkFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.090"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Shark-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="07sharkFinal"
        geometry={nodes["07sharkFinal"].geometry}
        material={materials["Material.090"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Shark-transformed.glb");
