/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t --transform --keepnames --precision 2 public/models/animals/Sheep.glb -o app/components/models/animals/Sheep.tsx 
Files: public/models/animals/Sheep.glb [126.98KB] > /Users/mendsalbert/Documents/safariVerse/app/components/models/animals/Sheep-transformed.glb [22.99KB] (82%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["10sheepFinal"]: THREE.Mesh;
  };
  materials: {
    ["Material.088"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/Sheep-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="10sheepFinal"
        geometry={nodes["10sheepFinal"].geometry}
        material={materials["Material.088"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/animals/Sheep-transformed.glb");
